#!/usr/bin/perl -w
#Usage: ./frMethylCorr.pl [minimumDepth] < sample_methylFreq.txt
#   sample_methylFreq.txt: the methylFreq file generated by bisReadMapper.pl

use strict;
use Statistics::LSNoHistory;
my %cpgTable;
my $minDepth = $ARGV[0];
$minDepth = 50 if (!$minDepth);
while(my $line = <STDIN>){
        my @fields = split(/\t/, $line);
        #next if($fields[3] <$minDepth);
	next if($fields[4] ne 'CG');
        my $chr = $fields[0];
        my $pos = $fields[1];
	#$pos-- if($fields[2] eq 'C');
        my %alleleFreq;
        my $Fct;
	$fields[2] = "C" if($fields[2] eq "-");
	$fields[2] = "W" if($fields[2] eq "+");
        for(my $i=5; $i<scalar(@fields); $i+=2){
                $alleleFreq{$fields[$i]}=$fields[$i+1];                 
                $Fct += $fields[$i+1] if($fields[$i]=~ /[CT]/);
        }
        next if (!$Fct || $Fct/$fields[3] < 0.9);
        #my $methylLevel = sprintf("%3.2f", $alleleFreq{'C'}? $alleleFreq{'C'}/$Fct : 0);
	$alleleFreq{'C'} = 0 if(!$alleleFreq{'C'});
        $cpgTable{$chr . ":" .$pos}->{$fields[2]}->{'C'} += $alleleFreq{'C'};
        $cpgTable{$chr . ":" .$pos}->{$fields[2]}->{'CT'} += $Fct;
        
}

my $corrStat = Statistics::LSNoHistory->new;
my $N=0;
foreach my $index (keys(%cpgTable)){
        if($cpgTable{$index}->{'W'} && $cpgTable{$index}->{'C'}){
			#print $index,"\t";			
			#print $cpgTable{$index}->{'W'}->{'methylFreq'}, "\t", $cpgTable{$index}->{'C'}->{'methylFreq'}, "\n";
			next if($cpgTable{$index}->{'W'}->{'CT'} < $minDepth || $cpgTable{$index}->{'C'}->{'CT'} < $minDepth);
			my $m_W = $cpgTable{$index}->{'W'}->{'C'}/$cpgTable{$index}->{'W'}->{'CT'};
			my $m_C = $cpgTable{$index}->{'C'}->{'C'}/$cpgTable{$index}->{'C'}->{'CT'};
			#$corrStat->append_point($cpgTable{$index}->{'W'}->{'methylFreq'},$cpgTable{$index}->{'C'}->{'methylFreq'});
			$corrStat->append_point($m_W, $m_C);
			$N++;
        }
}
print  "N=$N\tr=", $corrStat->pearson_r,"\n";
undef %cpgTable; 
