#PBS -N SRR10070127
#PBS -l nodes=1:ppn=1
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/methylation/pancrease/WGBS/temp/temp/
#PBS -e /gpfs/home/guosa/hpc/methylation/pancrease/WGBS/temp/temp/
cd /gpfs/home/guosa/hpc/methylation/pancrease/WGBS/temp
fastq-dump --split-files SRR10070127
bismark --bowtie2 --phred33-quals --multicore 1 --fastq -L 32 -N 0 -D 5 -R 1 /gpfs/home/guosa/hpc/db/hg19/bismark -1 SRR10070127_1.fastq -2 SRR10070127_2.fastq -o ./
