#PBS -N SRR10070126
#PBS -l nodes=1:ppn=16
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/methylation/pancrease/WGBS/temp/
#PBS -e /gpfs/home/guosa/hpc/methylation/pancrease/WGBS/temp/
cd /gpfs/home/guosa/hpc/methylation/pancrease/WGBS
bismark --bowtie2 --phred33-quals -p 6 --fastq -L 32 -N 0 -D 5 -R 1 /gpfs/home/guosa/hpc/db/hg19/bismark -1 SRR10070126_1.fastq -2 SRR10070126_2.fastq -o ./
