#PBS -N Human_BALL_hyperdiploid_Lee-Human-2015.meth.bw
#PBS -l nodes=1:ppn=1
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/methylation/methbase/temp/
#PBS -e /gpfs/home/guosa/hpc/methylation/methbase/temp/
cd /gpfs/home/guosa/hpc/methylation/methbase
bigWigToWig Human_BALL_hyperdiploid_Lee-Human-2015.meth.bw Human_BALL_hyperdiploid_Lee-Human-2015.meth.bw.wig
