#PBS -N Human_Colon_Tumor_Primary_Ziller-Human-2013.meth.bw
#PBS -l nodes=1:ppn=1
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/methylation/methbase/temp/
#PBS -e /gpfs/home/guosa/hpc/methylation/methbase/temp/
cd /gpfs/home/guosa/hpc/methylation/methbase
bigWigToWig Human_Colon_Tumor_Primary_Ziller-Human-2013.meth.bw Human_Colon_Tumor_Primary_Ziller-Human-2013.meth.bw.wig
