---
title: "MHB.enrich.TFBS"
author: "Shicheng Guo"
date: "Monday, January 04, 2016"
output: html_document
---

TO do the enrichment analysis for MHB regions, I only put the result in the disscussion section. I don't know whether Dr. Zhang will remove them. 

```{r}
setwd("/home/shg047/monod/phase3")
source("bedEnrichmentTest.R")

setwd("/home/shg047/db/hg19/encode")
ref=list.files(pattern="*hg19.bed")
# ref=c("LAD.hg19.bed","LOCK.hg19.bed","Coloncancer.small.DMR.PMC3145050.hg19.bed","VMR.charm.PMID20844285.hg19.bed","Hic.common.boundary.hESC.IMR90.hg19.bed","Hic.topological.domain.IMR90.hg19.bed","Hic.topological.domain.hESC.hg19.bed","CpGI.hg19.bed","CpG.Shore.hg19.bed")

#### Part A (bed1 <-bed1, bed2<-bed2)
setwd("/home/shg047/monod/phase3")
observation<-c()
expectation<-c()
ratio<-c()
fc<-c()
pvalue<-c()

for(i in ref){
  bed1="/home/shg047/monod/methyblock/WGBS_pooled_mappable_bins.all_autosomes.mld_blocks_r2-0.5.bed"
  bed2=paste("/home/shg047/db/hg19/encode/",i,sep="")
  excl="/home/shg047/db/hg19/CRGmapability.hg19.exclude.bed"
  assembly="hg19"
  nbed1=read.table(bed1)
  nbed2=read.table(bed2)
  rlt<-bedEnrichmentTest(bed1=bed1,bed2=bed2,excl=excl,iteration=100,assembly)
  observation=c(observation,rlt$observation)
  expectation=c(expectation,mean(rlt$expectation))
  fc=c(fc,rlt$observation/mean(rlt$expectation))
  ratio=c(ratio,rlt$observation/nrow(nbed1))
  pvalue=c(pvalue,rlt$pvalue)
}
out<-data.frame(ref,observation,expectation,ratio,fc,pvalue)
write.table(out,file="mhb.TFBS.WGBS_pooled_mappable_bins.all_autosomes.mld_blocks_r2-0.5.bedenrichment.result.partA.txt",sep="\t",quote=F,row.names=F,col.names=T)
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


