library("BART")
library("Rtsne")  
library("ggplot2")  
library("readxl")
library("BayesTree")
library("randomForest")
library("tidyverse")
library("caret")
library("MASS")
beta<-read.table("Table.S1.txt",head=T,sep="\t")
ROC<-read_xlsx("Table.S2.txt",sheet=1)
input<-data
fit1 <- (bayesglm(Phen ~ LenMed,family=binomial,data=input,na.action=na.omit))
fit2 <- (bayesglm(Phen ~ LenMean,family=binomial,data=input,na.action=na.omit))
fit3 <- (bayesglm(Phen ~ LenSD,family=binomial,data=input,na.action=na.omit))
summary(fit1)
summary(fit2)
summary(fit3)
