#PBS -N Human_HCC1954_BRCA_Hon-Human-2012.meth.bw
#PBS -l nodes=1:ppn=1
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/methylation/methbase/brca/temp/
#PBS -e /gpfs/home/guosa/hpc/methylation/methbase/brca/temp/
cd /gpfs/home/guosa/hpc/methylation/methbase/brca
bigWigToWig Human_HCC1954_BRCA_Hon-Human-2012.meth.bw Human_HCC1954_BRCA_Hon-Human-2012.meth.bw.wig
